### ISSUE TITLE
Suggest using value instead of function call for certain functions

### ISSUE THREAD

**Issue by samdphillips** [jackfirth/resyntax#128]
These are just a few similar ones off the top of my head this morning.

```
(+ a) => a

(string-append s) => s

;; maybe this one only if there are no formatting directives in the string
(format "some string") => "some string"

```

**Comment by jackfirth** [comment]
Definitely a good idea. There's some precedent too, as there's already a resyntax rule for `(append l) => l`. Feel free to send a PR (lately I've been focused more on the internals of resyntax than on adding new rules).
