### ISSUE TITLE
Suggest using ellipses with `->` instead of `#:rest` with `->*`

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#130]
Contracts like this:

```scheme
(->* (foo? bar?) #:rest (listof baz?) result?)
```

Can be expressed more simply with `->` and ellipses, like this:

```scheme
(-> foo? bar? baz? ... result?)
```

This only works for non-dependent contracts on functions without optional arguments and whose rest arguments are guarded uniformly with a `listof` contract.

**Comment by sorawee** [comment]
Technically, `#:rest` of `any/c` would be equivalent to `(listof any/c)` in this context, though I don't think there would be a lot of `#:rest any/c` in practice.
