### ISSUE TITLE
Suggest using test directly instead of `(if <test> #t #f)`

### ISSUE THREAD

**Issue by samdphillips** [jackfirth/resyntax#139]
Instead of
```
(if <test> #t #f)
```
use `<test>`.

Similarly if the branches are swapped suggest `(not <test>)`.

**Comment by samdphillips** [comment]
If `<test>` returns a non-boolean value then
```
(if <test> #t #f)
```
means something different than
```
<test>
```

**Comment by samdphillips** [comment]
From @jackfirth:
> I think having a syntax class that matches common expressions known to produce booleans only would be the way to go

**Comment by countvajhula** [comment]
A couple of other rules:
```
(if a a/#t b) => (or a b)
(if a b #f) => (and a b)
```

More ideas in [this SO thread](https://stackoverflow.com/questions/64082423/how-to-convert-cond-statements-that-produces-a-boolean-value-into-an-expression/64093079#64093079).

**Comment by samdphillips** [comment]
As I re-read this today, I thought a good coarse check would be to see if the test was a procedure call and if the procedure name ended with a `?`.  And of course, @jackfirth added precisely that :)
