### ISSUE TITLE
Comment-out unused/dead code 

### ISSUE THREAD

**Issue by jessealama** [jackfirth/resyntax#14]
I'm not sure if this entirely fits into the intended scope of resyntax; I kinda think it does, but I also can see why it wouldn't. The  idea would be to comment out dead code in a module. I'm keeping things simple here. My intended use case is: I usually explicitly enumerate the bindings I provide in my modules; I rarely use stuff like `(provide (all-defined-out)`. In this case, it should be fairly clear whether a toplevel binding is actually used. In such a case, it would be great if the resyntax would comment out that code. Just put a `#;` (followed by a newline) in front of it. Like this:

````
#lang racket/base

(provide f)

(define (f x) (add1 (* x x)))

(define (g x) (f (+ x x)))
````

gets rewritten to

````
#lang racket/base

(provide f)

(define (f x) (add1 (* x x)))

#;
(define (g x) (f (+ x x)))
````

Other tools in a code QA pipeline could identify this commented-out code. I'd be happy if resyntax would simply identify it; no need to be harsh and delete it.

As mentioned, the appearance of `(provide (all-defined-out))` at the toplevel defeats the rewriting I'm describing here. There may be other `provide` subforms that cause this rewriting to bail out.

**Comment by jackfirth** [comment]
I definitely want this. I don't know how to fit it into `resyntax` though, which only looks at single expressions in isolation and doesn't know anything about the usage sites of bindings in those expressions. Closing this as out of scope for `resyntax`, but definitely keeping it in my drawer of ideas for other tools.
