### ISSUE TITLE
Manually triggering post-rules

### ISSUE THREAD

**Issue by Metaxal** [jackfirth/resyntax#16]
The designer of a rule may know that the rhs of its rule may contain code that can be simplified.
Then, if applying all existing rules is too expensive (though I really want a mode that does that automatically), the rule itself could propose next rules to apply.
For example:
```racket
(define-refactoring-rule smurf
  #:literals (if begin)
  [(smurf x x y z)
   (if x x z)
   #:trigger (if-to-and if-to-when)])
```

**Comment by jackfirth** [comment]
I think this isn't useful now that `resyntax fix` supports running multiple passes, so I'm closing this for now.

**Comment by jackfirth** [comment]
I think this isn't useful now that `resyntax fix` supports running multiple passes, so I'm closing this for now.
