### ISSUE TITLE
Suggest using `dict-ref` instead of `hash-ref`/`assoc` etc.

### ISSUE THREAD

**Issue by dannypsnl** [jackfirth/resyntax#165]
As the title described, `dict-ref` can handle more kinds of associated data structures, using it as default can relax the code for future changes, should be a good idea?

**Comment by jackfirth** [comment]
If the code is already using `hash-ref`, then changing it to `dict-ref` doesn't change anything, so users won't see much reason to accept the suggestion. I think this could make more sense in cases where a dict is _converted_ to a hash just so someone can use `hash-ref`, but I've never seen code like that in the wild. Have you got a link to some code that would benefit from this suggestion?

**Comment by dannypsnl** [comment]
The situation I have is quite specific. The outer scope use hash to collect bindings, but when type checking local terms, it would be nice if it didn’t try to modify the parent scope. Hence, convert it to list by hash->list is a nice choice. But if the lookup function would like to behavior normally for both kind of environment context, use dict-ref is more proper choice, performance here don’t get huge impact.

But this maybe not general enough to get performance issue everywhere then?

**Comment by jackfirth** [comment]
That sounds like something that's outside of Resyntax's domain to solve. You might be interested in the ongoing effort in Rhombus to provide better collection APIs. I'm working on a [generic collections framework](https://github.com/racket/rhombus-prototype/discussions/201) that would provide a way to wrap collections with read-only views, which sounds like it fits your use case.
