### ISSUE TITLE
De Morgan rewrites frequently make code more confusing

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#187]
Resyntax currently rewrites [this code](https://github.com/racket/drracket/pull/611/files/8dc532eb09d2283a2631b6bd5e3baa1ac60ce7b3#diff-e77b16344cef184f38c3163e22536b4f5f48940f262e85b40b0fa64b6150d299L875-L877):

```scheme
(define (different-slots? item-key next-item-key)
  (or (not (= (quotient item-key 100)
              (quotient next-item-key 100)))
      (not (= (sgn item-key)
```

To this:

```scheme
(define (different-slots? item-key next-item-key)
  (not (and (= (quotient item-key 100)
               (quotient next-item-key 100)) (= (sgn item-key)
                                                (sgn next-item-key)))))
```

This is equivalent and technically smaller, but it's less clear what's going on. The De Morgan's laws rewrites in Resyntax frequently have this problem: they make boolean expressions significantly harder to understand and only marginally smaller. They're not worth keeping around and should be removed.

**Comment by Metaxal** [comment]
Just an idea: how about proposing such a rewrite if the code size
difference is large enough?

**Comment by Metaxal** [comment]
Using a command-line-tunable parameter for example

**Comment by jackfirth** [comment]
That might be nice. I'd prefer to see some examples of real code that it would help with first.

**Comment by Metaxal** [comment]
Of course. Just something to keep in mind, perhaps.
