### ISSUE TITLE
Suggest map => for/list, similar to for-each => for

### ISSUE THREAD

**Issue by cloudrac3r** [jackfirth/resyntax#193]
Just like the `for-each` => `for` conversion, some `map`s should be converted to `for/list`.

They can use the same heuristics to detect whether they should be converted (i.e. having a large enough body)

Previously discussed here: https://github.com/racket/drracket/pull/611#discussion_r1131935922

**Comment by jackfirth** [comment]
Found another instance where this would help: in [this code](https://github.com/racket/racket/blob/837c819ce1caf734ee90f38c76b8b76eda11ac4e/racket/collects/pkg/private/addl-installs.rkt#L109-L117) after replacing the `(apply append (for/list ...))` with a single `(for*/list ...)`, the `map` can be fused into that `for*/list`.
