### ISSUE TITLE
For loop suggestions

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#20]
Example:

```
(foldl
  (lambda (x y)
    (+ <expression referencing y> x))
  0
  numbers)

=>

(for/sum ([y (in-list numbers)])
  <expression referencing y>)
```

**Comment by Metaxal** [comment]
I saw a suggestion about `andmap` to a for loop somewhere. Be careful here because there's more contract checking with `andmap` and `map` than with `for`, regarding the lengths of the lists which must be equal (`for` doesn't check that). It should be fine if it's only about single lists though.

**Comment by jackfirth** [comment]
I'm closing this for now since 1) there's some basic `for` loop support now and 2) the issue is very broad. Instead I'll file separate issues for specific `for` loop improvements as I think of them.
