### ISSUE TITLE
Use #:result in for/fold

### ISSUE THREAD

**Issue by sorawee** [jackfirth/resyntax#215]
This one may be difficult, but might be worth trying.

Previously, `for/fold` doesn't support `#:result`, so the code could look like this:

```
(define (my-fun)
  .....
  (define-values (a b) 
    (for/fold ([a ...] [b ...]) (....)
       .....))
  (+ a b))
```

But with `#:result`, we can simplify it to simply:

```
(define (my-fun)
  .....
  (for/fold ([a ...] [b ...] #:result (+ a b)) (....)
     .....)
```

More generally, the any `define-values` with `for/fold` expression can move the single "tail computation" expression into `#:result` and remove the wrapping `define-values`. It's worth doing this when the "tail computation" is simple.

**Comment by jackfirth** [comment]
That is indeed tricky. Got some examples of code in the wild this could clean up? Maybe we could get more mileage out of only detecting simpler cases, like when only one of the `define-values` bindings is used.
