### ISSUE TITLE
No refactoring on #lang racket

### ISSUE THREAD

**Issue by sorawee** [jackfirth/resyntax#229]
Why doesn't 

```
#lang racket

(define (test)
  (let ([x 1])
    (+ x 1)))
```

get refactored, while 

```
#lang racket/base

(define (test)
  (let ([x 1])
    (+ x 1)))
```

does? I agree that there are refactoring that could be unsafe in `#lang racket` (which is safe in `#lang racket/base`), but this particular case seems always fine?

**Comment by jackfirth** [comment]
Just haven't gotten around to it. I was planning to add this when I figured out how to support only applying refactoring rules when their suggestions don't require inserting new imports into the module, but Alex figured that out for me as a byproduct of #166. So I think we can do this now.
