### ISSUE TITLE
Recommend using definitions instead of let bindings

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#23]
This is probably one of the most common and useful refactorings that `resyntax` could suggest. It's the most common source of rightward drift in Racket code, and the pervasive support of internal definitions makes it easy to eliminate.

**Comment by Metaxal** [comment]
This will require some care though re. shadowing, since a sequence of `define`s is not strictly equivalent to `let`. For example, I sometimes use `let` to explicitly shadow an identifier to make sure I don't use the wrong one by mistake.

**Comment by jackfirth** [comment]
Yup, it will need some analysis to avoid firing on cases where `let` actually offers something that `define` doesn't, such as cases of shadowing.

**Comment by jackfirth** [comment]
Possible rule, inspired by [this](https://github.com/racket/scribble/blob/154ffe21b5c7f13f5b08f424a45b40ff549bacdd/scribble-lib/scribble/search.rkt#L62):

```scheme
(and expr
    (let ([id rhs] ...) body ...))

=>

(cond
  [(not expr) #false] ;; negated to keep the guard case before the main logic
  [else
   (define id rhs) ...
   body ...])
```

**Comment by jackfirth** [comment]
Gonna call this mostly done for now, as the analysis works correctly for `let`, `let*`, and `let-values`. There's plenty of cases where it could do more, but the`refactorable-let-expression` and `block-with-refactorable-let-expression` make those cases easy to write rules for on an as-needed basis. Further requests for let-to-define migrations should go in separate, more specific issues.
