### ISSUE TITLE
->* #:rest to -> ...

### ISSUE THREAD

**Issue by sorawee** [jackfirth/resyntax#235]
Many contracts use `->*` with `#:rest` to contract a function with a rest argument.

However, `->*` is difficult to read. 

Since Racket 6.5, `->` supports `...`, which can be used to support the rest argument as well.

Since `->` is much easier to read, when applicable, `->* #:rest` should be rewritten to `-> ...`.

**Comment by jackfirth** [comment]
The `arrow-contract-with-rest-to-arrow-contract-with-ellipses` rule implements this, though I don't remember when I wrote that one.

**Comment by sorawee** [comment]
You even had #130!

**Comment by jackfirth** [comment]
Great minds think alike 🙂
