### ISSUE TITLE
Recommend using hash-ref! instead of hash-ref with hash-set!

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#24]
Found in [scribble/core](https://github.com/racket/scribble/blob/154ffe21b5c7f13f5b08f424a45b40ff549bacdd/scribble-lib/scribble/core.rkt#L627):

```scheme
(or (hash-ref tags t #f)
    (let ([key (list* 'gentag
                      (hash-count tags)
                      (collect-info-gen-prefix ci))])
      (hash-set! tags t key)
      key))
```

I think this is equivalent to:

```scheme
(hash-ref! tags t (λ () (list* 'gentag (hash-count tags) (collect-info-gen-prefix ci))))
```

**Comment by jackfirth** [comment]
Oh dear, this isn't equivalent if the hash table contains `#f` values for any of the keys. Maybe ignoring that possibility is reasonable?

**Comment by Metaxal** [comment]
I don't think it's 'reasonable', but it could still be suggested to the user, while also mentioning the caveat(s).

This rule can be applied if it can be proven that `tags` can never contain the value `#f`. But proving this requires knowing all uses of `tags`, or that there's a contract/type saying it can't contain `#f`.

My opinion is that opt-out or default resyntax rules should be 100% safe. But you can have several layers of rules I suppose.

**Comment by Metaxal** [comment]
Another option is to force-push the refactoring, run the test suite and if nothing breaks it stays :grin:

**Comment by jackfirth** [comment]
Closing this for now since without types it's too risky.
