### ISSUE TITLE
Remove duplicate provided identifiers

### ISSUE THREAD

**Issue by jessealama** [jackfirth/resyntax#28]
If I `provide` an identifier multiple times, it could be replaced with a single occurrence of the identifier. Thus,

````
(provide
  a
  b
  a)             
````

could be rewritten to just

````
(provide 
  a
  b)
````

**Comment by jackfirth** [comment]
This seems doable. Does it need to catch duplication across multiple `provide` forms, or would duplication within a single `provide` form be enough? The latter is much easier to implement currently. Also, how common an issue is this in practice? Links to files/commits/pull requests where this rule would have helped would be great.

**Comment by jessealama** [comment]
I guess it's pretty rare. I'm not drawing on experience with PRs or other high-quality code -- I'm reflecting on my own poor code!

**Comment by jessealama** [comment]
Doing this for a single `provide` form would be a good (and easier) start.
