### ISSUE TITLE
CLI prints replacements with too much indentation

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#33]
The CLI prints replacements with the same indentation they have in the source code. So in this code:

```scheme
#lang racket/base
(outer-stuff
        (define (f)
          (let ([x 1])
            (g))))
```

The CLI prints this:

```
Internal definitions are recommended instead of let expressions, to reduce nesting.

3         (define (f)
4           (let ([x 1])
5             (g)))

3         (define (f)
4           (define x 1)
5             (g)))
```

This makes replacements kind of hard to read in isolation. It would be better if the CLI just stripped all the leading indentation and printed the above replacement like this:

```
Internal definitions are recommended instead of let expressions, to reduce nesting.

3 (define (f)
4   (let ([x 1])
5     (g)))

3 (define (f)
4   (define x 1)
5   (g))
```

It should be easy to make this change by tweaking the implementation of the [`resyntax/code-snippet`](https://github.com/jackfirth/resyntax/blob/master/code-snippet.rkt) module.

**Comment by Metaxal** [comment]
Or use a re-indenter? 
racket-mode has one, that was mostly extracted from DrRacket I believe—it would be great if it were a package on its own.

**Comment by jackfirth** [comment]
If there was something already available it'd be nice to use it, but in the short term I'm good with just implementing something simple and specific to `resyntax`.
