### ISSUE TITLE
Refactorings drop comments sometimes

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#5]
This could be fixed by checking if there's any comments in a syntax object that aren't preserved by the output. The output will preserve comments in subexpressions that are `syntax-original?`, so we have to check if there are comments in the span of the input syntax which are not contained within the spans of the output subexpressions that are `syntax-original?`. Not sure how to do that yet.

**Comment by jackfirth** [comment]
One possible fix for this would be to introduce formatting markup (like `NEWLINE`) that rules can use to say what spans between syntax objects should be preserved. Example:

```scheme
(define-refactoring-rule if-else-cond-to-cond
  #:literals (if cond)
  [((~and original-if if) condition
   then-branch
   (~and original-tail ((~and original-cond cond) first-clause clause ...)))
   (original-cond
     NEWLINE (ORIGINAL-CONTENT-BETWEEN original-if condition)
     [(ORIGINAL-SPLICE condition then-branch)]
     (ORIGINAL-CONTENT-BETWEEN then-branch original-tail)
     (ORIGINAL-CONTENT-BETWEEN original-cond first-clause)
     (ORIGINAL-SPLICE first-clause clause ...))])
```

Where `(ORIGINAL-CONTENT-BETWEEN stx1 stx2)` means "insert exactly the text between `stx1` and `stx2` into this position" and `(ORIGINAL-SPLICE stx1 stx2 stx3 ...)` means `stx1 (ORIGINAL-CONTENT-BETWEEN stx1 stx2) stx2 (ORIGINAL-CONTENT-BETWEEN stx2 stx3) stx3 ...`.

**Comment by Metaxal** [comment]
How about extending the read table to read comments as syntax? This way you would even be able to move them around a bit if necessary.

Also, unrelated, but would it be possible to use a particular prefix (even like just a symbol) instead of all-caps?

**Comment by jackfirth** [comment]
Reading the comments as syntax sounds interesting, but I don't know how to do it (especially for an arbitrary `#lang`).

Prefix: sure, though I don't really have any preferences here.

**Comment by Metaxal** [comment]
Can you currently support more than s-exp languages?

I suggest the duck prefix `\_@°<` for clarity and visual happiness (or not).

**Comment by Metaxal** [comment]
@sorawee says:
> I think you can do that by adjusting readtable, but I don’t think it will play well with the rest of the system.
> For example, if you have (if x #| abc |# y z). Now if have 4 subforms. Suddenly every macro needs to take care of these comment syntax object.
> What might make more sense is to attach the comment information to the enclosing syntax object’s syntax property.

**Comment by sorawee** [comment]
That assumes that you create your own `#lang` though. For existing `#lang racket/base`, I guess it's not as straightforward. You can potentially textually substitute `racket/base` with `resyntax/racket/base` and rerun the program, but I don't know how well it's gonna be.

**Comment by jackfirth** [comment]
> Can you currently support more than s-exp languages?

Practically no, theoretically yes. I'd need to add some hook to look up a submodule in the `#lang` and extract a function that turns a syntax object back into a string. If I had that, then I could support any lang that chose to implement such a submodule.

**Comment by Metaxal** [comment]
I suggest to start with s-exp, and have something robust for it first—maybe keeping in mind the other languages.
