### ISSUE TITLE
Refactoring triple comparisons

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/resyntax#76]
Saw this code in the discord server:

```scheme
(and (< num 10) (> num -10))
```

Resyntax ought to be able to rewrite that to this:

```scheme
(< -10 num 10)
```

**Comment by Metaxal** [comment]
Too bad you can't easily turn 
```racket
(and (< num 10) (>= num -10))
```
into
```racket
(< -11 num 10)
```
since you need to know that num is an integer

**Comment by jackfirth** [comment]
That's probably fine. This is likely to come up with people who don't know that the comparison procedures accept multiple arguments, so as long as some of their comparisons get caught, it will teach them that they can refactor the other comparisons too.

**Comment by jackfirth** [comment]
(And I might prefer to write that example you gave with `rebellion/base/range` anyway.)
